- 적용 전 UI/MainPage.html
> 메인페이지 각 영역 분리

- 적용 전 UI/MainPage.html
> UI 파일 데코 업로드

- 적용 전 UI/SignUp.html
> Sign Up 페이지 틀 제작

- 적용 전 UI/PasswordChange.html
> 비밀번호 변경 페이지 UI 틀 제작

- 적용 전 UI/MainPage.html
> 메인페이지 애니메이션 적용

- 적용 전 UI/EditProfile.html
- 적용 전 UI/MyPage.html
- 적용 전 UI/PasswordChange.html
마이페이지: 프로필 사진과 이름 등급 이메일 표시 / 프로필수정 , 비밀번호 변경 버튼 제작
프로필수정: 프로필 이미지변경 / 이름 / 이메일 변경가능 / 등급은 읽기전용으로 표시만 가능 / 저장,취소 버튼 제작 / + 프로필이미지변경은 버튼,프로필창,드로그앤드롭으로 변경 가능 3가지 기능 추가
비밀번호변경: 현재 비밀번호,새로운비밀번호,새로운비밀번호확인 3가지의 input 창 표기 type -> password type 으로 지정 / 눈모양 아이콘 클릭시 비밀번호 표시되게 기능 추가 , 저장,취소버튼제작
> 마이페이지,프로필수정,비밀번호 변경 페이지 UI 틀 제작

- 적용 전 UI/PostPage.html
자주 묻는 하는 질문 클릭하면 질문 리스트 나오고 질문 리스트 클릭하면 질문 답변 볼수 있게 했고 figma UI 상에는 게시글 상단에서 세부적인 메뉴 관리하던거 왼쪽으로 영역 따로 분리했습니다. 수정 해야 할 사항 있으면 알려 주세요
> 고객지원 페이지 UI 구현 했습니다.

- 적용 전 UI/DetailPostPage.html
- 적용 전 UI/PostPage.html
:postPage( 게시물 목록 페이지 ) / detailPostPage ( 게시물 상세 페이지 )
postPage.html : 화면 div영역 화면 맞추기(아직 구현중입니다.)
detailPostPage.html : 게시물 상세페이지 추천수, 조회수, 댓글, 게시물 목록, 왼쪽 메뉴바 추가
> [2024/10/25]Zeus

- 소스트리 연결 후 확인.txt
> 소스트리 연결 후 테스트

- 적용 전 UI/EnrollPostPage.html
- 적용 전 UI/smartediter/demo/css/ko_KR/smart_editor2.css
EnrollPostPage.html : 작성하기 버튼 오류 발견하여 수정하고 css 파일에 오류가 있어 수정하였습니다.
> [2024/10/28] Zeus: EnrollPostPage.html( 게시물 작성 페이지)  

- 적용 전 UI/DetailPostPage.html
- 적용 전 UI/EnrollPostPage.html
- 적용 전 UI/PostPage.html
EnrollPostPage.html( 게시물 작성 페이지), DetailPostPage(게시물 상세 페이지), PostPage(게시물 목록 페이지)  class 이름 카멜케이스로 되어 있던 부분 dash(-) 로 수정 후 DetailPostPage.html에 목록 부분에서 목록으로 돌아가는 버튼 하나 추가.
> [2024/10/25]Zeus: EnrollPostPage.html( 게시물 작성 페이지), DetailPostPage(게시물 상세 페이지),  PostPage(게시물 목록 페이지) 수정

- 적용 전 UI/EnrollPostPage.html
EnrollPostPage.html( 게시물 작성 페이지) : 게시물 작성 중 취소 버튼 구현, 왼쪽 메뉴바 부분 위치 부자연스러운 부분 조정.
> [2024/10/28]Zeus: EnrollPostPage.html( 게시물 작성 페이지)

- jcm-react/src/components/CompIntroduce.jsx
- jcm-react/src/components/User/ChangePwd.jsx
- jcm-react/src/components/User/MyPage.jsx
- jcm-react/src/components/User/SignIn.jsx
- jcm-react/src/components/common/FooterPage.jsx
- jcm-react/src/components/common/MenuBar.jsx
- jcm-react/src/components/mainPage/MainDescribe.jsx
- jcm-react/src/components/mainPage/MainEmail.jsx
- jcm-react/src/components/mainPage/MainInfo.jsx
- jcm-react/src/components/mainPage/MainMethod.jsx
- jcm-react/src/components/mainPage/MainReferences.jsx
- jcm-react/src/components/mainPage/MainSimulation.jsx
- jcm-react/src/components/post/PostPage.jsx
프로젝트 내에 있는 class 속성 들어가 있는 태그들 className으로 수정
> [2024/10/28] Zeus : jcm-react 프로젝트 수정

- jcm-react/README.md
- jcm-react/package-lock.json
- jcm-react/package.json
- jcm-react/src/components/CompIntroduce.jsx
- jcm-react/src/css/CompIntroduce.css
README.md : 기존내용 삭제후 모듈 추가 주석 추가 ( 모듈추가 양식 / [날짜] 추가된모듈 )
CompIntroduce.jsx : 기존 코드에 Naver Map API 기능 하단 추가 ( 정상작동 )
CompIntroduce.css : 기존 코드에 Naver Map API 관련 css 추가 ( 기존 반응형에 해당 기능 반응형 추가 ) / 충돌 발생하는 코드 수정
package.json : react-helmet 모듈 추가 ( ver. 6.1.0 )
> [2024-10-29] Download

- jcm-react/src/components/mainPage/PageMain.jsx
- jcm-react/src/css/Main.css
> [2024/10/29]Rocomi

- jcm-react/src/components/User/MyPage.jsx
> [2024-10-29] Rocomi

- jcm-react/src/components/User/SignIn.jsx
> [2024-10-29]Rocomi

- jcm-react/src/App.js
- jcm-react/src/components/post/FrequentlyQuestions.jsx
- jcm-react/src/components/post/PostPage.jsx
- jcm-react/src/css/FrequentlyQuestions.css
FrequentlyQuestions (자주 묻는 질문) 링크로 분리
> [2024-10-29] 2weeks

- jcm-react/src/components/mainPage/MainReferences.jsx
Main페이지: 4번째 구간에서  icon이미지를 접근하려고 할 때 오류가 나던 부분을 수정했습니다.
> [2024.10.29] Zeus : Main페이지

- jcm-react/src/components/common/MenuBar.jsx
- jcm-react/src/components/user/ChangePwd.jsx
- jcm-react/src/components/user/EditProfile.jsx
- jcm-react/src/components/user/MyPage.jsx
- jcm-react/src/components/user/SignIn.jsx
User폴더 user로 폴더명 변경
MenuBar에 결제관리 탭 추가
> [2024-10-30]Rocomi

- jcm-react/src/App.js
- jcm-react/src/components/Main.jsx
커밋 후 FooterPage import 안되어 있던거 수정하고 Main.jsx 에서 사용하지 않는 Footer 제거 했습니다. 
+ npm add chart.js   해주셔야 코드 정상 작동 합니다.
> [2024.10.30]Zeus 커밋 후 코드 정리

- jcm-react/src/css/Main.css
메인페이지 4번째 구간 텍스트 단어 기준으로 줄바꿈 되는 스타일 추가
> [2024.10.30] Zeus : 메인페이지 4번째 구간

- jcm-react/src/App.js
- jcm-react/src/components/Main.jsx
- jcm-react/src/components/guide/Guide.jsx
- jcm-react/src/css/guide/Guide.css
> [2024-10-30] 2week

- jcm-react/src/components/mainPage/MainSimulation.jsx
- jcm-react/src/css/Main.css
메인 페이지 css 수정 : 메인 페이지에 box 비율 크거나 작은 부분들 있어서 box 비율 수정 했습니다.
> [2024.10.30]Zeus : 메인 페이지 css 수정

- jcm-react/src/App.js
- jcm-react/src/components/common/MenuBar.jsx
- jcm-react/src/components/payment/PaymentHistory.jsx
- jcm-react/src/components/payment/PaymentMethod.jsx
- jcm-react/src/css/payment/PaymentHistory.css
- jcm-react/src/css/payment/PaymentMethod.css
결제관리 페이지 html로 구현되어 있던 파일 참고하여 리액트 적용 시켰습니다.
> [2024.10.30] Zeus : 결제관리 페이지

- jcm-react/src/App.js
- jcm-react/src/components/admin/AdminSideBar.jsx
- jcm-react/src/components/mainPage/MainReferences.jsx
- jcm-react/src/css/Main.css
- jcm-react/src/css/user/SignIn.css
[메인 페이지]
- 3번째 항목 (쉽고빠르게만드는웹사이트) 부분 크게 키움
- 4번째 항목 (눈에 띄는 웹사이트를...) 부분 아이콘 하단의 설명 부분에 대한 텍스트 정렬 변경 (* text-wrap 관련 스타일 참고)
- 5번째 항목 (웹사이트 제작의 모든 고민을 해결해...), 6번째 항목 (간단한 사용, 결과물 선택) 부분 크기 줄임
- 6번째 항목 (Contect us) 간격 동일하게 (margin/padding)  적용
[고객지원]
- 간격 조절 ( 상단 타이틀 부분 , 자주묻는질문, 지원 목록 )
[로그인/회원가입 - sign in]
- 다크테마 적용
> [2024-10-31] 2weeeks

- jcm-react/src/components/post/Questions.jsx
- jcm-react/src/css/Main.css
메인 4번째 구간 css에 단어 기준 줄바꿈 스타일 추가하고 게시판 페이지에서 자주하는 질문 컴포넌트는 문의사항 게시판에만 나오게 수정했습니다.
> [2024.10.30] Zeus : Main.css , Questions.jsx 수정

- jcm-react/package-lock.json
- jcm-react/src/App.js
- jcm-react/src/components/admin/AdminChat.jsx
- jcm-react/src/components/admin/AdminTopBar.jsx
- jcm-react/src/components/admin/Customer.jsx
- jcm-react/src/components/admin/Posts.jsx
- jcm-react/src/components/admin/QnA.jsx
- jcm-react/src/components/admin/Subscribe.jsx
- jcm-react/src/components/post/EnrollPost.jsx
- jcm-react/src/components/post/FreeBoard.jsx
- jcm-react/src/components/post/Notice.jsx
- jcm-react/src/components/post/PostPage.jsx
- jcm-react/src/components/post/ProjectBoard.jsx
- jcm-react/src/components/post/Questions.jsx
- jcm-react/src/css/admin/Admin.css
- jcm-react/src/css/admin/Chat.css
- jcm-react/src/css/admin/Customer.css
- jcm-react/src/css/admin/Posts.css
- jcm-react/src/css/admin/QnA.css
- jcm-react/src/css/admin/Subscribe.css
- jcm-react/src/css/post/EnrollPost.css
게시물 작성 페이지 html로 만들어 놨던거 리액트 적용 했고 css 작업 조금 더 해야 합니다.
그리고 관리자 쪽 페이지 아래 이슈내용 수정 완료 했습니다. 
- Dashboard : UI 설계와 동일하게 배치 간격 조절 필요. 왼쪽으로 치우쳐져 있음
- 검색창의 용도 확인
- Subscribe : UI 설계 내용 확인 필요. 차트 누락됨
- Customer : 타이틀 부분 표시안됨
- Posts : 타이틀 표시안됨. 전체적으로 크기가 너무 커보임 조절 필요
- Q&A : 게시판이므로 목록형식보다는 테이블 형식으로 표시하는 것을 권장
> [2024.10.31] Zeus : 관리자 페이지들 ui 수정 , 게시물 작성 페이지 리액트 적용.

- jcm-react/src/components/guide/Guide.jsx
- jcm-react/src/css/guide/Guide.css
1. 가이드 페이지 UI 추가
2. 가이드 페이지 React 적용
> [2024-10-31] 2weeks

- jcm-react/src/components/post/ProjectBoard.jsx
- jcm-react/src/css/post/FreeBoard.css
- jcm-react/src/css/post/PostPage.css
- jcm-react/src/css/post/ProjectBoard.css
- jcm-react/src/css/post/Questions.css
> 2024-10-31 2weeks

- jcm-react/README.md
- jcm-react/package-lock.json
- jcm-react/package.json
- jcm-react/src/components/CompIntroduce.jsx
- jcm-react/src/components/guide/Guide.jsx
- jcm-react/src/css/CompIntroduce.css
- jcm-react/src/css/guide/Guide.css
1. framer-motion 추가 ( 애니메이션 모듈 )
2. CompIntroduce 에서 팀원소개 부분 애니메이션 효과 추가
3. Guide 결제 화면에 애니메이션 효과 추가
> [2024-10-31] 2week

- jcm-react/src/components/user/ChangePwd.jsx
- jcm-react/src/components/user/EditProfile.jsx
- jcm-react/src/components/user/MyPage.jsx
- jcm-react/src/css/user/ChangePwd.css
- jcm-react/src/css/user/EditProfile.css
- jcm-react/src/css/user/MyPage.css
마이프로필 페이지와 부속 페이지들 css 흰색테마 적용 했습니다.
> [2024.10.24]Zeus : 마이프로필 페이지와 프로필 관련 부속 페이지 css 수정

- jcm-react/src/css/user/ChangePwd.css
비밀번호 변경 페이지 css 적용 안된 거 있어서 수정 후 커밋합니다.
> [2024.10.24]Zeus : 비밀번호 변경 페이지 수정 

- jcm-react/package-lock.json
- jcm-react/package.json
- jcm-react/src/components/post/EnrollPost.jsx
- jcm-react/src/css/post/EnrollPost.css
리액트 적용 완료 했고 게시글 작성부분 react-quill 라이브러리 다운 받아 적용 시켜서 npm add react-quill 해주셔야 정상 작동 됩니다.
> [2024.10.31] 게시물 작성 페이지 구현 : 게시물 작성 페이지 100프로 구현작업 완료.

- jcm-react/README.md
README 파일에 라이브러리 추가한거 업데이트했습니다.
> [2024.10.31] Zeus : README 파일 업데이트

- jcm-react/src/css/payment/PaymentHistory.css
- jcm-react/src/css/payment/PaymentMethod.css
- jcm-react/src/css/user/ProjectHistory.css
> [2024.10.31] Zeus : 테이블 수정

- jcm-react/src/components/Main.jsx
- jcm-react/src/components/mainPage/Chat.jsx
Main.jsx : 채팅창에서 스크롤시 fullpage 기능이 적용되어 메인페이지와 같이 스크롤 되던 오류 문제 해결
Chat.jsx : 채팅창에서 스크롤시 fullpage 기능이 적용되어 메인페이지와 같이 스크롤 되고 엔터키로 채팅내용을 전송하는 이벤트가 작동하지 않는 오류 해결
> [2024-11-01] Download

- jcm-react/src/components/post/FrequentlyQuestions.jsx
- jcm-react/src/css/post/FrequentlyQuestions.css
자주묻는 useState로 데이터 담고 출력하게 수정 후 토글방식으로 대답 나올 수 있게 수정.
> [2024.11.01]Zeus : 자주묻는 질문 컴포넌트 수정

- jcm-react/src/App.js
- jcm-react/src/components/post/BoardTable.jsx
- jcm-react/src/components/post/DetailPost.jsx
- jcm-react/src/components/post/EnrollPost.jsx
- jcm-react/src/components/post/FreeBoard.jsx
- jcm-react/src/components/post/Notice.jsx
- jcm-react/src/components/post/ProjectBoard.jsx
- jcm-react/src/components/post/Questions.jsx
- jcm-react/src/css/post/DetailPost.css
- jcm-react/src/css/post/FreeBoard.css
- jcm-react/src/css/post/Notice.css
- jcm-react/src/css/post/PostMenu.css
- jcm-react/src/css/post/ProjectBoard.css
- jcm-react/src/css/post/Questions.css
게시물 테이블 분리한 부분에 pageNation, 작성하기 버튼 추가하여 분리하고 DetailPostPage css 수정
> [2024.11.01] Zeus : 고객지원 페이지 css 수정 

- jcm-react/src/components/post/DetailPost.jsx
- jcm-react/src/components/post/EnrollPost.jsx
- jcm-react/src/css/post/DetailPost.css
상세 게시물 페이지, 게시물 작성 페이지 다시 메뉴로 돌아가는 버튼 추가.
> [2024.11.01] Zeus : 상세 게시물 페이지, 게시물 작성 페이지 수정

- jcm-react/src/components/mainPage/MainPage.jsx
MainPage.jsx : 메인페이지에서 발생하던 svg 이벤트로 인학 렉 문제를 해결함 / 첫번째 svg 가 보여지는 영역에서 벗어나면 해당 svg 이벤트를 잠시 멈춤 / 다시 영역으로 돌아가면 svg 이벤트 실행으로 렉 문제 일부 해결
> [2024-11-01] Donwload : 메인페이지 svg 효과 렉걸리는 문제 해결

- .gitignore
- Servers/.project
- Servers/.settings/org.eclipse.wst.server.core.prefs
- jcm/.gitattributes
- jcm/.gitignore
- jcm/.mvn/wrapper/maven-wrapper.properties
- jcm/mvnw
- jcm/mvnw.cmd
- jcm/pom.xml
- jcm/src/main/java/com/jocomi/jcm/JcmApplication.java
- jcm/src/main/java/com/jocomi/jcm/ServletInitializer.java
- jcm/src/main/java/com/jocomi/jcm/interceptor/LoginInterceptor.java
- jcm/src/main/java/com/jocomi/jcm/interceptor/WebMvcConfig.java
- jcm/src/main/java/com/jocomi/jcm/member/controller/MemberController.java
- jcm/src/main/java/com/jocomi/jcm/member/vo/Member.java
- jcm/src/main/java/com/jocomi/jcm/model/mapper/MemberMapper.java
- jcm/src/main/java/com/jocomi/jcm/service/MemberService.java
- jcm/src/main/resources/application.properties
- jcm/src/main/resources/mappers/MemberMapper.xml
- jcm/src/test/java/com/jocomi/jcm/JcmApplicationTests.java
Spring-Boot 프로젝트 생성 및 관련 설정 
<Dependencies>
- Spring Web
- Thymeleaf
- Lombok
- Spring Boot Dev Tools
- gson
<properties>
- port (7777)
- datasource (oracle.jdbc.OracleDriver)
- mybatis setting
class 추가, 작성 
- LoginInterceptor, WebMvcConfig 
- member.controller.MemberController (loginMember() 작성)
- member.vo.Member (일부작성)
- service.MemberService (loginMember()작성)
Interface 추가
-  model.mapper.MemberMapper (loginMember 작성)
> [2024-11-01]Rocomi

- .gitignore
> [2024-11-04]Rocomi

- jcm-react/README.md
- jcm-react/package-lock.json
- jcm-react/package.json
- jcm-react/src/components/mainPage/Chat(backup).jsx
- jcm-react/src/components/mainPage/Chat.jsx
- jcm-react/src/components/payment/PaymentMethod.jsx
Chat.jsx : 채널톡 API 적용 / 모듈설치 / 연동확인
PayMentMethod.jsx : const payhistory -> const PayMentMethod 로 변경
Chak(backup).jsx : 이전 채팅 파일 백업 ( API 오류 발생시 롤백용 )
> [2024-11-04] Donwload / 채팅 API 적용 및 모듈설치 / 결제관리 코드 수정

- jcm-react/src/App.js
- jcm-react/src/components/common/MenuBar.jsx
- jcm-react/src/components/setup/WebSetUp.jsx
- jcm-react/src/components/setup/WebSetUpForm.jsx
- jcm-react/src/css/setup/WebSetUp.css
- jcm-react/src/css/setup/WebSetUpForm.css
추후 웹 제작 View API 가져오면 추가로 구현 예정.
> [24-11-05] 2week 웹 제작 구현

- jcm-react/src/components/payment/PaymentMethod.jsx
- jcm-react/src/components/user/SignIn.jsx
- jcm-react/src/css/payment/PaymentMethod.css
- jcm/src/main/java/com/jocomi/jcm/member/controller/MemberController.java
- jcm/src/main/java/com/jocomi/jcm/member/vo/Member.java
- jcm/src/main/java/com/jocomi/jcm/model/mapper/MemberMapper.java
- jcm/src/main/java/com/jocomi/jcm/service/MemberService.java
- jcm/src/main/resources/mappers/MemberMapper.xml
로그인 기능 구현했습니다. 중간 커밋이고 회원가입 성공 시 다시 로그인 창으로 가지게 하고 컨트롤러에서 리턴값 바꿔주는 작업 해야합니다.
> [2024.11.05]Zeus : 로그인 기능 구현

- jcm-react/src/css/post/FrequentlyQuestions.css
[고객지원]
- 문의 사항 > 자주묻는 질문 : 마우스 오버 시 부자연스러운 배경색 변경
> [2024-11-05] Download / 문의사항 > 자주묻는질문 마우스 오버시 부자연스러운 배경색 변경

- jcm-react/src/components/user/SignIn.jsx
> [24-11-07] 2week 회원가입 데이터타입 변경

- jcm-react/src/components/post/EnrollPost.jsx
- jcm-react/src/css/post/EnrollPost.css
> [2024.11.07] 게시물 작성 페이지 css 수정.

- jcm-react/src/components/post/BoardTable.jsx
> [2024.11.07]Zeus : 게시물 작성 버튼 오류 해결.

- jcm-react/package-lock.json
- jcm-react/package.json
- jcm-react/src/components/user/AddressModal.jsx
- jcm-react/src/components/user/SignIn.jsx
- jcm-react/src/css/user/AddressModal.css
- jcm-react/src/css/user/SignIn.css
> [24-11-08] 2week 주소 모달

- jcm-react/src/App.js
- jcm-react/src/components/user/MyPage.jsx
- jcm-react/src/components/user/SignIn.jsx
- jcm/src/main/java/com/jocomi/jcm/interceptor/WebMvcConfig.java
- jcm/src/main/java/com/jocomi/jcm/member/controller/MemberController.java
- jcm/src/main/java/com/jocomi/jcm/model/mapper/MemberMapper.java
- jcm/src/main/java/com/jocomi/jcm/model/vo/Member.java
- jcm/src/main/java/com/jocomi/jcm/service/MemberService.java
- jcm/src/main/resources/mappers/member/MemberMapper.xml
마이페이지 기능 구현 ( 80% 프로필 이미지 불러오는 기능 구현중 )
> [2024-11-08] Download / 마이페이지 기능 구현

- jcm-react/src/components/post/DetailPost.jsx
- jcm/src/main/java/com/jocomi/jcm/board/controller/AnnouncementController.java
- jcm/src/main/java/com/jocomi/jcm/board/controller/EnquiryController.java
- jcm/src/main/java/com/jocomi/jcm/board/controller/FreeController.java
- jcm/src/main/java/com/jocomi/jcm/board/controller/ProjectController.java
- jcm/src/main/java/com/jocomi/jcm/board/model/mapper/AnnouncementBoardMapper.java
- jcm/src/main/java/com/jocomi/jcm/board/model/mapper/ProjectBoardMapper.java
- jcm/src/main/java/com/jocomi/jcm/board/service/AnnouncementService.java
- jcm/src/main/java/com/jocomi/jcm/comment/controller/BoardCommentController.java
- jcm/src/main/java/com/jocomi/jcm/comment/model/mapper/CommentMapper.java
- jcm/src/main/java/com/jocomi/jcm/comment/model/vo/BoardComment.java
- jcm/src/main/java/com/jocomi/jcm/comment/service/CommentService.java
게시글 댓글 불러오는 기능 구현, 게시글 댓글 작성하는 기능 구현. sql문 충돌나는 부분있어서 파일 폐기 해서 다시 작성후 따로 커밋하겠습니다.
> [2024.11.08]Zeus : 게시글 댓글 불러오는 기능 구현, 게시글 댓글 작성하는 기능 구현. 

- jcm-react/src/components/user/AddressModal.jsx
- jcm-react/src/components/user/SignIn.jsx
- jcm/src/main/java/com/jocomi/jcm/interceptor/WebMvcConfig.java
- jcm/src/main/java/com/jocomi/jcm/member/controller/MemberController.java
CORS 통신 기능 추가
외부에서 접속시 localhost:3000 으로 접속되면서 DB 연동 문제발생한점 전역IP 로 해결 완료
+ ( 추후 다른 코드들도 수정 예정 )
> [2024-11-10] Download / CORS 통신 기능 추가 / 외부접속시 통신오류 해결

- jcm-react/src/components/user/EditProfile.jsx
- jcm-react/src/components/user/SignIn.jsx
- jcm/src/main/java/com/jocomi/jcm/interceptor/WebMvcConfig.java
- jcm/src/main/java/com/jocomi/jcm/member/controller/MemberController.java
- jcm/src/main/java/com/jocomi/jcm/model/mapper/MemberMapper.java
- jcm/src/main/java/com/jocomi/jcm/service/MemberService.java
- jcm/src/main/resources/mappers/member/MemberMapper.xml
로그인,회원가입 기능 정상 작동
회원가입시 아이디,이메일,전화번호 중복체크 기능 추가
CORS 통신 일부 수정
> [2024-11-11] Download / 로그인,회원가입 기능 완료 / 아이디,이메일,전화번호 중복체크 기능 추가

- jcm-react/src/components/post/EnquiryBoard.jsx
- jcm-react/src/components/post/ProjectBoardTable.jsx
- jcm/src/main/java/com/jocomi/jcm/board/controller/AnnouncementController.java
- jcm/src/main/java/com/jocomi/jcm/board/controller/EnquiryController.java
- jcm/src/main/java/com/jocomi/jcm/board/controller/FreeController.java
- jcm/src/main/java/com/jocomi/jcm/board/controller/ProjectController.java
- jcm/src/main/java/com/jocomi/jcm/board/model/mapper/AnnouncementBoardMapper.java
- jcm/src/main/java/com/jocomi/jcm/board/model/mapper/EnquiryBoardMapper.java
- jcm/src/main/java/com/jocomi/jcm/board/model/mapper/FreeBoardMapper.java
- jcm/src/main/java/com/jocomi/jcm/board/model/mapper/ProjectBoardMapper.java
- jcm/src/main/java/com/jocomi/jcm/board/service/AnnouncementService.java
- jcm/src/main/java/com/jocomi/jcm/board/service/FreeService.java
- jcm/src/main/java/com/jocomi/jcm/board/service/ProjectService.java
- jcm/src/main/java/com/jocomi/jcm/comment/service/CommentService.java
- jcm/src/main/java/com/jocomi/jcm/member/controller/MemberController.java
> [2024.11.13] Zeus : 11월12일 커밋사항 날라간거 다시 올립니다..

- jcm-react/src/components/mainPage/MainDescribe.jsx
- jcm-react/src/components/mainPage/MainSimulation.jsx
- jcm-react/src/components/setup/WebSetUpForm.jsx
- jcm-react/src/css/Main.css
- jcm/src/main/java/com/jocomi/jcm/api/controller/AIController.java
> [2024-11-13]Rocomi

- jcm-react/src/components/post/AnnouncementBoardTable.jsx
- jcm-react/src/components/post/EnquiryBoardTable.jsx
- jcm-react/src/components/post/FreeBoardTable.jsx
- jcm-react/src/components/post/ProjectBoardTable.jsx
- jcm-react/src/components/post/boarditems/DetailPost.jsx
- jcm-react/src/components/post/boarditems/EnrollPost.jsx
- jcm/src/main/java/com/jocomi/jcm/board/model/mapper/AnnouncementBoardMapper.java
- jcm/src/main/java/com/jocomi/jcm/board/model/mapper/EnquiryBoardMapper.java
- jcm/src/main/java/com/jocomi/jcm/board/model/mapper/FreeBoardMapper.java
- jcm/src/main/java/com/jocomi/jcm/board/model/mapper/ProjectBoardMapper.java
- jcm/src/main/java/com/jocomi/jcm/comment/model/mapper/CommentMapper.java
- jcm/src/main/java/com/jocomi/jcm/recommend/model/mapper/RecommendMapper.java
- jcm/src/main/resources/application.properties
- jcm/src/main/resources/mappers/board/AnnouncementboardMapper.xml
- jcm/src/main/resources/mappers/board/EnquiryboardMapper.xml
- jcm/src/main/resources/mappers/board/FreeboardMapper.xml
- jcm/src/main/resources/mappers/board/ProjectboardMapper.xml
- jcm/src/main/resources/mappers/comment/Comment.xml
- jcm/src/main/resources/mappers/recommend/RecommendMapper.xml
mapper 파일 분리작업. 요청주소 동적으로 요청 할 수 있게 설정.
> [2024.11.14] Zeus : mapper 파일 분리작업. 요청주소 동적으로 요청 할 수 있게 설정.

- jcm-react/src/components/mainPage/MainReferences.jsx
- jcm/src/main/java/com/jocomi/jcm/comment/model/mapper/CommentMapper.java
- jcm/src/main/resources/mappers/comment/CommentMapper.xml
댓글 불러오는 중 오류사항 발생하여  수정 후 재 커밋합니다.
> [2024.11.14]Zeus : 댓글 불러오는 중 오류사항 발생하여  수정 후 재 커밋합니다.

- jcm-react/src/components/user/ChangePwd.jsx
- jcm-react/src/components/user/EditProfile.jsx
- jcm-react/src/components/user/MyPage.jsx
- jcm-react/src/css/user/ChangePwd.css
- jcm-react/src/css/user/EditProfile.css
- jcm-react/src/css/user/MyPage.css
- jcm/src/main/java/com/jocomi/jcm/member/controller/MemberController.java
- jcm/src/main/java/com/jocomi/jcm/model/mapper/MemberMapper.java
- jcm/src/main/java/com/jocomi/jcm/service/MemberService.java
- jcm/src/main/resources/mappers/member/MemberMapper.xml
마이페이지,프로필수정 반응형 css 기능 추가
비밀번호 변경 기능,css 구현
> [2024-11-14] Download / 마이페이지,프로필수정 반응형 css 추가 / 비밀번호변경 기능 추가

- jcm-react/src/components/post/EnquiryBoardTable.jsx
- jcm/src/main/resources/mappers/board/AnnouncementboardMapper.xml
- jcm/src/main/resources/mappers/board/EnquiryboardMapper.xml
- jcm/src/main/resources/mappers/board/FreeboardMapper.xml
- jcm/src/main/resources/mappers/board/ProjectboardMapper.xml
게시물 작성시 나는 오류 수정하고 비공개 게시물 접근 오류 수정했습니다.
> [2024.11.14] Zeus : 게시물 작성시 나는 오류 수정하고 비공개 게시물 접근 오류 수정했습니다.

- jcm-react/src/components/mainPage/MainEmail.jsx
> [2024-11-14]Rocomi

- jcm-react/src/App.js
- jcm-react/src/components/user/NaverCallback.jsx
- jcm-react/src/components/user/NaverLoginButton.jsx
- jcm-react/src/components/user/SignIn.jsx
- jcm/src/main/java/com/jocomi/jcm/member/controller/MemberController.java
- jcm/src/main/java/com/jocomi/jcm/model/mapper/MemberMapper.java
- jcm/src/main/java/com/jocomi/jcm/naver/model/vo/NaverProfile.java
- jcm/src/main/java/com/jocomi/jcm/naver/response/NaverProfileResponse.java
- jcm/src/main/java/com/jocomi/jcm/naver/service/NaverLoginService.java
- jcm/src/main/java/com/jocomi/jcm/service/MemberService.java
- jcm/src/main/resources/mappers/member/MemberMapper.xml
> [2024-11-15]Rocomi

- jcm/src/main/java/com/jocomi/jcm/config/WebMvcConfig.java
> [2024-11-15]Rocomi webconfig 파일 복구 및 경로 변경

- jcm-react/src/components/common/EmptyUser.jsx
- jcm-react/src/components/payment/PaymentHistory.jsx
- jcm-react/src/components/payment/PaymentMethod.jsx
- jcm-react/src/components/setup/DBSetUpForm.jsx
- jcm-react/src/components/setup/FunctionSetUpForm.jsx
- jcm-react/src/components/setup/WebSetUpForm.jsx
- jcm-react/src/css/common/EmptyUser.css
로그인 안할 시 인터셉터 설정
emptyUser 페이지로 이동
> [2024-11-15]Rocomi 인터셉터 설정 및 emptyUser페이지 작성

- jcm/src/main/java/com/jocomi/jcm/recomment/controller/RecommentController.java
- jcm/src/main/java/com/jocomi/jcm/recomment/model/mapper/RecommentMapper.java
- jcm/src/main/java/com/jocomi/jcm/recomment/model/vo/Recomment.java
- jcm/src/main/java/com/jocomi/jcm/recomment/service/RecommentService.java
- jcm/src/main/resources/mappers/comment/CommentMapper.xml
- jcm/src/main/resources/mappers/recomment/RecommentMapper.xml
답글 작성하는부분 백엔드쪽만 구현 했습니다. 현재 프론트쪽은 파일이 꼬여서 추후에 구현 하겠습니다. 그리고 sql 파일 올려야 할 게 있는데 충돌 나서 해결 후 추후 같이 올리겠습니다.
> [2024.11.15] Zeus : 답글 작성 백엔드 구현

- jcm-react/src/components/common/MenuBar.jsx
- jcm-react/src/css/common/MenuBar.css
상단메뉴바 반응형 기능 추가
웹사이트 축소시 햄버거 메뉴 버튼 표기
> [2024-11-19] Download / 상단메뉴바 반응형 기능 추가 / 햄버거 메뉴 추가

- jcm-react/src/App.js
- jcm-react/src/components/admin/AdminDashboard.jsx
- jcm-react/src/components/common/EmptyAdmin.jsx
- jcm-react/src/shared/axiosAdmin.js
> [2024-11-20]Rocomi 관리자 페이지 인터셉터 적용 중

- jcm-react/src/App.js
- jcm-react/src/components/admin/AdminSideBar.jsx
- jcm-react/src/components/common/MenuBar.jsx
admin 페이지 이동시 /admin/~~~ 페이지로 이동되는 잘못된 URL 주소 변경
> [2024-11-20] Download / admin 페이지 URL 규칙 수정

- jcm-react/src/shared/axiosAdmin.js
> [2024-11-20]Rocomi 관리자 페이지 인터셉터 작성 완료

- jcm-react/src/components/admin/AdminChat.jsx
- jcm-react/src/components/admin/Customer.jsx
- jcm-react/src/components/admin/Posts.jsx
- jcm-react/src/components/admin/QnA.jsx
- jcm-react/src/components/admin/Subscribe.jsx
> [2024-11-20]Rocomi 관리자페이지 전체 인터셉터 적용

- jcm-react/src/components/user/MyPage.jsx
- jcm/src/main/java/com/jocomi/jcm/member/controller/MemberController.java
- jcm/src/main/java/com/jocomi/jcm/model/mapper/MemberMapper.java
- jcm/src/main/java/com/jocomi/jcm/model/vo/Member.java
- jcm/src/main/java/com/jocomi/jcm/service/MemberService.java
- jcm/src/main/resources/mappers/member/MemberMapper.xml
마이페이지-> 등급 기능 추가 PAYMENT 테이블에서 PAY_PRODUCT 컬럼의 값을 최신날짜 기준으로 가져와서 표기
> [2024-11-20] Download / 마이페이지 등급 기능 추가

- jcm-react/package-lock.json
- jcm-react/package.json
- jcm-react/src/components/user/NaverLoginButton.jsx
- jcm-react/src/components/user/SignIn.jsx
- jcm/src/main/java/com/jocomi/jcm/payment/controller/PaymentController.java
네이버 로그인 api 스크립트 오류 해결 및 비밀번호 제약조건 추가
> [24-11-20] 2week

- jcm-react/src/components/admin/Posts.jsx
- jcm-react/src/components/post/EnquiryBoardTable.jsx
- jcm-react/src/components/post/boarditems/DetailPost.jsx
- jcm-react/src/components/post/boarditems/EnrollPost.jsx
게시판 부분 로그인 안되어 있을 때 상태관리 구현했습니다.
> [2024.11.20]Zeus : 게시판 부분 로그인 안되어 있을 때 상태관리 구현했습니다.

- jcm-react/src/components/admin/AdminDashboard.jsx
- jcm/src/main/java/com/jocomi/jcm/admin/controller/AdminController.java
프론트 , 백엔드 서버 연결 상태 체크후 어드민대쉬보드 페이지에서 상태 체크 표기 기능 구현
> [2024-11-20] Download / 관리자대쉬보드 페이지에서 Web Server 상태 체크 기능 구현

- jcm-react/src/components/admin/Posts.jsx
- jcm-react/src/components/admin/QnA.jsx
- jcm-react/src/components/post/boarditems/DetailPost.jsx
- jcm-react/src/css/admin/Posts.css
- jcm-react/src/css/admin/QnA.css
관리자 페이지에서 게시물 관리하는 부분 구현, 게시물에 프로필 이미지 불러올 수 있게 구현.
> [2024.11.20] Zeus : 관리자 페이지에서 게시물 관리하는 부분 구현, 게시물에 프로필 이미지 불러올 수 있게 구현.

- DB/JCM MEMBER.sql
> [2024-11-21] Download / Member 쿼리문 수정후 재업로드

- jcm-react/src/components/admin/Customer.jsx
- jcm-react/src/components/user/EditProfile.jsx
- jcm-react/src/components/user/FindId.jsx
- jcm-react/src/components/user/NaverCallback.jsx
- jcm-react/src/components/user/NaverLoginButton.jsx
- jcm-react/src/components/user/ProjectHistory.jsx
- jcm-react/src/components/user/SetPassword.jsx
- jcm-react/src/components/user/SignIn.jsx
프론트 -> 백엔드 요청주소 localhost -> 서버 실행 동적 IP 로 요청하도록 코드 변경
> [2024-11-21] Download / 프론트 서버 요청 IP 주소 변경

- jcm-react/src/components/post/ProjectBoardTable.jsx
- jcm-react/src/components/post/boarditems/DetailPost.jsx
- jcm-react/src/components/post/boarditems/EnrollPost.jsx
게시물 구글, 네이버 로그인시 작성자 표시 이메일 @앞부분 보여지게 하고 프로필 이미지 기본이미지 불러오게 코드작성.
> [2024.11.21] Zeus : 게시물 작성자 표시 수정, 프로필 이미지 경로 수정.

- jcm-react/src/components/admin/Report.jsx
report 페이징 처리시 boardType 누락 되는 부분 있어서 수정
> report 페이징 처리시 boardType 누락 되는 부분 있어서 수정.

- jcm/src/main/java/com/jocomi/jcm/board/controller/BoardController.java
> [2024.11.22] Zeus : boardController 콘솔 찍히는거 제거

- jcm/src/main/java/com/jocomi/jcm/board/controller/BoardController.java
- jcm/src/main/java/com/jocomi/jcm/report/controller/ReportController.java
진짜 마지막 수정 사항입니다. error 메세지 뜨는 부분 안뜨게 수정했습니다. 컨트롤러 console 찍히는 부분 제거.
> [2024.11.22] Zeus : 진짜 마지막 수정 사항입니다. error 메세지 뜨는 부분 안뜨게 수정했습니다. 컨트롤러 console 찍히는 부분 제거.

- jcm-react/src/components/guide/Guide.jsx
- jcm-react/src/css/guide/Guide.css
- jcm/src/main/java/com/jocomi/jcm/payment/controller/PaymentController.java
- jcm/src/main/java/com/jocomi/jcm/payment/model/mapper/PaymentMapper.java
- jcm/src/main/java/com/jocomi/jcm/payment/service/PaymentService.java
- jcm/src/main/java/com/jocomi/jcm/report/controller/ReportController.java
- jcm/src/main/resources/mappers/payment/PaymentMapper.xml
> [2024.11.25] Zeus : 가이드 css 수정.
